<?php
// $Id$

/*
 * Implementation of hook_requirements().
 */
function swfupload_requirements($phase) {
  $t = get_t();
  $requirements = array('swfupload' => array('title' => $t('SWFUpload')));
  $path = drupal_get_path('module', 'swfupload') .'/swfupload';
  if ((file_exists($path .'/SWFUpload.swf') && file_exists($path .'/SWFUpload.js')) ||
    (file_exists($path .'/swfupload.swf') && file_exists($path .'/swfupload.js'))) {
    $requirements['swfupload']['value'] = 'Installed';
  }
  else {
    $requirements['swfupload']['value'] = $t('Missing files');
    $requirements['swfupload']['description'] = $t('You must install the minimalistic <a href="@swfupload">SWFUpload</a> library to %swfuploadpath.', array('@swfupload' => 'http://www.swfupload.org', '%swfuploadpath' => $path));
    $requirements['swfupload']['severity'] = REQUIREMENT_ERROR; 
  }
  return $requirements;
}

function swfupload_generate($name = 'swfupload_default') {
  static $cssadded = FALSE;
  _swfupload_add_js($name);
  $path = drupal_get_path('module', 'swfupload');
  if ($cssadded == FALSE) {
    $cssadded = TRUE;
    drupal_add_css($path .'/swfupload.css');
  }
  return _swfupload_interface($name);
}

/**
 * Implementation of hook_menu().
 */
function swfupload_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    $items[] = array(
      'path' => 'swfupload/js',
      'callback' => 'swfupload_js',
      'access' => TRUE, //user_access('upload files'),
      'type' => MENU_CALLBACK
    );
    $items[] = array('path' => 'flash_upload',
      'callback' => '_swfupload_swfupload',
      'access' => TRUE, //_swfupload_user_access(arg(2)),
      'type' => MENU_CALLBACK
    );    
  }
  return $items;
}

function _swfupload_user_access($key) {
  /*
  THIS IS A BIG SECURITY HOLE - PLEASE HELP FIXING IT
  the code below should work, but for some reason arg(1) contains all kind of different values but not the sid which 
  it is supposed to contain.
  you can check the content of variables in this function by writing them to a table in the database or to a file
  
  $result = db_query("SELECT uid FROM {sessions} WHERE sid = '%s'", $key);
  $session = db_fetch_array($result);
  
  
  if (!$session) {
    return FALSE;
  }
  else {    
    $user = user_load(array('uid' => $session['uid']));
    return user_access('upload files', $user);
  }
  */
  return TRUE;
}


function _swfupload_swfupload() {
  // Load drupal session and get session vars
  $name = $_POST['name'];
  $session_id = $_POST['PHPSESSID'];
  session_id($_POST['PHPSESSID']);
  
  session_decode(sess_read($session_id));
  
  global $user;
  $user = user_load(array('uid'=> $_POST['uid']));
  
  // Check for upload error
	if (!isset($_FILES["Filedata"]) || !is_uploaded_file($_FILES["Filedata"]["tmp_name"]) || $_FILES["Filedata"]["error"] != 0) {
		header("HTTP/1.1 500 File Upload Error");
		if (isset($_FILES["Filedata"])) {
			echo $_FILES["Filedata"]["error"];
		}
		exit(0);
	}
	
  // Get unique key - I use that since I had troubles using count() in this context
  $index = mt_rand();
  if (!$index) $index = 0;
  $key = "upload_".$index;

  // Adapt to drupal files structure

  $_FILES['files']['name'][$key] = $_FILES['Filedata']['name'];
  $_FILES['files']['type'][$key] = $_FILES['Filedata']['type'];
  $_FILES['files']['tmp_name'][$key] = $_FILES['Filedata']['tmp_name'];
  $_FILES['files']['error'][$key] = $_FILES['Filedata']['error'];
  $_FILES['files']['size'][$key] = $_FILES['Filedata']['size'];  
  
  // The following code is taken from the upload.module:
  
  // Clean up old file previews if a post didn't get the user to this page.
  // i.e. the user left the edit page, because they didn't want to upload anything.

  if(count($_POST) == 0) {
    if (is_array($_SESSION['file_previews']) && count($_SESSION['file_previews'])) {
      foreach ($_SESSION['file_previews'] as $fid => $file) {
        file_delete($file->filepath);
      }
      unset($_SESSION['file_previews']);
    }
  }
  print_r($_SESSION);

  // $_SESSION['file_current_upload'] tracks the fid of the file submitted this page request.
  // form_builder sets the value of file->list to 0 for checkboxes added to a form after
  // it has been submitted. Since unchecked checkboxes have no return value and do not
  // get a key in _POST form_builder has no way of knowing the difference between a check
  // box that wasn't present on the last form build, and a checkbox that is unchecked.

  //unset($_SESSION['file_current_upload']);

  // Save new file uploads to tmp dir.
  if ($file = file_check_upload($key)) {

    // Scale image uploads.
    $file = _upload_image($file);
    

    $file->fid = $key;
    $file->source = $key;
    $file->list = variable_get('upload_list_default',1);
    $_SESSION['file_previews'][$key] = $file;
    // Store the uploaded fid for this page request in case of submit without
    // preview or attach. See earlier notes.
    $_SESSION['file_current_upload'] = $key;
    
    //module_invoke_all('swfupload', $name, array('file' => $file));
  }
  
  // write to drupal session 
  sess_write($session_id, session_encode());
  
  //global $user;
  //$user = user_load(array('uid'=> $uid));
  
  //print_r($_SESSION);
  echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" >
      <head><title>SWFUpload Revision 7.0 beta 2 Demo</title></head>
      <body><p>Upload Complete</p></body>
    </html>';
    exit(0);
  //}
}

/**
 * Implementation of hook_form_alter().
 */
function swfupload_form_alter($form_id, &$form) {
  if ($form_id == 'node_type_form' && isset($form['identity']['type'])) {
    $form['workflow']['upload'] = array(
      '#type' => 'radios',
      '#title' => t('Attachments'),
      '#default_value' => variable_get('upload_'. $form['#node_type']->type, 1),
      '#options' => array(t('Disabled'), t('Enabled')),
    );
  }

  if (isset($form['type'])) {
    $node = $form['#node'];
    if ($form['type']['#value'] .'_node_form' == $form_id && variable_get("upload_$node->type", TRUE)) {
      drupal_add_js('misc/progress.js');
      drupal_add_js('misc/upload.js');

      // Attachments fieldset
      $form['attachments'] = array(
        '#type' => 'fieldset',
        '#access' => user_access('upload files'),
        '#title' => t('File attachments'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#description' => t('Changes made to the attachments are not permanent until you save this post. The first "listed" file will be included in RSS feeds.'),
        '#prefix' => '<div class="attachments">',
        '#suffix' => '</div>',
        '#weight' => 30,
      );

      $form['attachments']['swfupload'] = array('#prefix' => '<div>', '#suffix' => '</div>', '#value' => _swfupload_interface());

      // Wrapper for fieldset contents (used by upload JS).
      $form['attachments']['wrapper'] = array(
        '#prefix' => '<div id="attach-wrapper">',
        '#suffix' => '</div>',
      );

      // Make sure necessary directories for upload.module exist and are
      // writable before displaying the attachment form.
      $path = file_directory_path();
      $temp = file_directory_temp();
      // Note: pass by reference
      if (!file_check_directory($path, FILE_CREATE_DIRECTORY) || !file_check_directory($temp, FILE_CREATE_DIRECTORY)) {
        $form['attachments']['#description'] =  t('File attachments are disabled. The file directories have not been properly configured.');
        if (user_access('administer site configuration')) {
          $form['attachments']['#description'] .= ' '. t('Please visit the <a href="@admin-file-system">file system configuration page</a>.', array('@admin-file-system' => url('admin/settings/file-system')));
        }
        else {
          $form['attachments']['#description'] .= ' '. t('Please contact the site administrator.');
        }
      }
      else {
        $form['attachments']['wrapper'] += _swfupload_form($node);
        $form['#attributes']['enctype'] = 'multipart/form-data';
      }
    }
  }
}

function _swfupload_form($node) {
  global $user;
  $path = drupal_get_path('module', 'swfupload');
  drupal_add_css($path .'/swfupload.css');
  _swfupload_add_js();  
  
  $form['#theme'] = 'upload_form_new';

  if (is_array($node->files) && count($node->files)) {
    $form['files']['#theme'] = 'upload_form_current';
    $form['files']['#tree'] = TRUE;
    foreach ($node->files as $key => $file) {
      $description = file_create_url((strpos($file->fid, 'upload') === FALSE ? $file->filepath : file_create_filename($file->filename, file_create_path())));
      $description = "<small>". check_plain($description) ."</small>";
      $form['files'][$key]['description'] = array('#type' => 'textfield', '#default_value' => (strlen($file->description)) ? $file->description : $file->filename, '#maxlength' => 256, '#description' => $description );

      $form['files'][$key]['size'] = array('#value' => format_size($file->filesize));
      $form['files'][$key]['remove'] = array('#type' => 'checkbox', '#default_value' => $file->remove);
      $attributes = $file->list ? array('checked' => 'checked') : array();
      $form['files'][$key]['list'] = array('#type' => 'checkbox',  '#default_value' => $file->list, '#attributes' => $attributes);      
      // if the file was uploaded this page request, set value. this fixes the problem
      // formapi has recognizing new checkboxes. see comments in _upload_prepare.
      if ($_SESSION['file_current_upload'] == $file->fid) {
        $form['files'][$key]['list']['#value'] = variable_get('upload_list_default',1);
      }
      $form['files'][$key]['filename'] = array('#type' => 'value',  '#value' => $file->filename);
      $form['files'][$key]['filepath'] = array('#type' => 'value',  '#value' => $file->filepath);
      $form['files'][$key]['filemime'] = array('#type' => 'value',  '#value' => $file->filemime);
      $form['files'][$key]['filesize'] = array('#type' => 'value',  '#value' => $file->filesize);
      $form['files'][$key]['fid'] = array('#type' => 'value',  '#value' => $file->fid);
    }
  }

  if (user_access('upload files')) {
    // This div is hidden when the user uploads through JS.
    $form['new'] = array(
      '#prefix' => '<div id="attach-hide">',
      '#suffix' => '</div>',
    );
    // $form['new']['upload'] = array('#type' => 'file', '#title' => t('Attach new file'), '#size' => 40);
    // The class triggers the js upload behaviour.
    $form['attach-url'] = array('#type' => 'hidden', '#value' => url('swfupload/js', NULL, NULL, TRUE), '#attributes' => array('class' => 'upload'));
    // Attach button turns into Refresh button
    $form['new']['attach'] = array('#type' => 'button', '#value' => t('Refresh'), '#name' => 'attach', '#id' => 'attach-button', '#attributes' => array('style' => 'margin-bottom: 25px;'));    
  }
  // Needed for JS
  $form['current']['vid'] = array('#type' => 'hidden', '#value' => $node->vid);
  return $form;
}

function _swfupload_interface($name = 'swfupload_default', $arguments = array()) {
  $uploadbuttontitle = isset($arguments['uploadbuttontitle']) ? $arguments['uploadbuttontitle'] : t('Browse');
  $cancelbuttontitle = isset($arguments['cancelbuttontitle']) ? $arguments['cancelbuttontitle'] : t('Cancel Queue');
  $interface = <<<EOT
  <div id="flash_$name" style="display: none;">
		<fieldset class="flash" id="uploadprogress_$name">
			<legend>Queue</legend>
		</fieldset>
		<div>
			<input type="button" value="$uploadbuttontitle" onclick="$name.selectFiles()" />
			<input id="cancelbutton_$name" type="button" value="$cancelbuttontitle" onclick="cancelQueue($name);" disabled="disabled" /><br />
		</div>
	</div>
	<div id="degraded_$name">
		<fieldset>
			<legend>Files</legend>
			<input type="file" name="anyfile1" /> (Any file)<br/>
		</fieldset>
		<div>
			<input type="submit" value="Submit Files" />
		</div>
	</div>
EOT;
  /*$interface = '<div id="SWFUploadTarget">
  <input name="files[upload]" class="form-file" id="edit-upload" size="40" type="file" />
  </div>
  <h4 id="queueinfo">'. t('Queue is empty') . '</h4>
  <div id="SWFUploadFileListingFiles"></div>
  <a class="swfuploadbtn" id="cancelqueuebtn" href="javascript:swfupload_cancelQueue();">'. t('Cancel queue') . '</a>';*/
  return $interface;
}

/**
 * Menu-callback for JavaScript-based uploads.
 */
function swfupload_js() {
  // We only do the upload.module part of the node validation process.
  $node = (object)$_POST;

  // Load existing node files.
  $node->files = upload_load($node);

  // Handle new uploads, and merge tmp files into node-files.
  _upload_prepare($node);
  _upload_validate($node);

  $form = _swfupload_form($node, TRUE);
  module_invoke_all('form_alter', 'swfupload_js', $form);
  $form = form_builder('swfupload_js', $form);
  $output = theme('status_messages') . drupal_render($form);

  // We send the updated file attachments form.
  print drupal_to_js(array('status' => TRUE, 'data' => $output));
  exit;
}

/**
 * Adds the javascript
 */ 
function _swfupload_add_js($name = 'swfupload_default', $arguments = array()) {
  global $user;
  $path = drupal_get_path('module', 'swfupload');
  drupal_add_js($path .'/swfupload/swfupload.js');
  drupal_add_js($path .'/callbacks.js');
  
  $upload_url = url('flash_upload', NULL, NULL, TRUE);
  $phpsessid = session_id();
  $flash_url = base_path() . $path .'/swfupload/swfupload.swf';
  $file_size_limit = empty($arguments['file_size_limit']) ? 99720 : $arguments['file_size_limit'];
  $file_types = empty($arguments['file_types']) ? '*.*' : $arguments['file_types'];
  $file_types_description = empty($arguments['file_types_description']) ? t('All Files') : $arguments['file_types_description'];
  $file_upload_limit = empty($arguments['file_upload_limit']) ? 0 : $arguments['file_upload_limit'];
	$file_queue_limit = empty($arguments['file_queue_limit']) ? 0 : $arguments['file_queue_limit'];
  
  $js = <<<EOT
    var $name;   
    function start_$name() {
      $name = new SWFUpload({
        // Backend Settings
        upload_url : "$upload_url",
        post_params: {
          "PHPSESSID" : "$phpsessid",
          "name" : "$name",
          "uid" : "$user->uid"
        },
        
        // File Upload Settings
        flash_url : "$flash_url",
        file_size_limit : "$file_size_limit",
        file_types : "$file_types",
        file_types_description : "$file_types_description",
        file_upload_limit : "$file_upload_limit",
				file_queue_limit : "$file_queue_limit",

				// Event Handler Settings (all my handlers are in the Handler.js file)
				file_dialog_start_handler : fileDialogStart,
				file_queued_handler : fileQueued,
				file_queue_error_handler : fileQueueError,
				file_dialog_complete_handler : fileDialogComplete,
				upload_start_handler : uploadStart,
				upload_progress_handler : uploadProgress,
				upload_error_handler : uploadError,
				upload_complete_handler : uploadComplete,
				file_complete_handler : fileComplete,

				// Flash Settings
				flash_url : "$flash_url",
				
				// UI Settings
				ui_container_id : "flash_$name",
				degraded_container_id : "degraded_$name",
				
        debug : true
      });
			$name.customSettings.progressTarget = "uploadprogress_$name";	// Add an additional setting that will later be used by the handler.
			$name.customSettings.cancelButtonId = "cancelbutton_$name";			// Add an additional setting that will later be used by the handler.
    };
    window.onload = start_$name;
EOT;
  drupal_add_js($js, 'inline');
}
